--L2 TRANSFORM

--TABLAS INE:

--1)CREAR TABLA L2_INE_ODS_2C1
CREATE TABLE [L2].L2_INE_ODS_2C1
(
  id_L2_ine_ods_2_c_1 BIGINT PRIMARY KEY IDENTITY(1,1)
, id_anio INT
, id_mes INT
, Autonomia VARCHAR(100)
, id_autonomia INT
, IPC DECIMAL(10,3)
)
;

--2)CREAR TABLA L2_INE_ODS_2C2
CREATE TABLE [L2].L2_INE_ODS_2C2
(
  id_L2_ine_ods_2_c_2 BIGINT PRIMARY KEY IDENTITY(1,1)
, id_anio INT
, id_mes INT
, IPC_PAN DECIMAL(10,3)
)
;

--3)CREAR TABLA L2_INE_ODS_2A_1_PIB
CREATE TABLE [L2].L2_INE_ODS_2A_1_PIB
(
  id_L2_ine_ods_2a_1_pib BIGINT PRIMARY KEY IDENTITY(1,1)
, id_anio INT
, Autonomia VARCHAR(100)
, id_autonomia INT
, PIB DECIMAL(10,3)
)
;

--4)CREAR TABLA L2_INE_2A2_AOD_NETO
CREATE TABLE [L2].L2_INE_2A2_AOD_NETO
(
  id_L2_ods_2a2_aod_neto BIGINT PRIMARY KEY IDENTITY(1,1)
, Año INT
, Valor DECIMAL(10,3)
)
;

--5)CREAR TABLA L2_INE_2A2_AOD_BRUTO
CREATE TABLE [L2].L2_INE_2A2_AOD_BRUTO
(
  id_L2_ods_2a2_aod_bruto BIGINT PRIMARY KEY IDENTITY(1,1)
, Año INT
, Valor DECIMAL(10,3)
)
;